### ISSUE TITLE
Problems with decay function in setup_r5

### ISSUE THREAD

**Issue by randl068** [ipeaGIT/r5r#227]
Hi all, apologies if this is just something on my end but I get this error on running the setup_r5 function with default parameters:

> r5r_core <- setup_r5(data_path)
>Error in setup_r5(data_path) : 
>  java.lang.NoClassDefFoundError: com/conveyal/r5/analyst/decay/DecayFunction

I am wondering if this is anyway related to issues with the IPEA server.

**Comment by mvpsaraiva** [comment]
Hi @randl068. 
One possible reason for this issue is that the R5 Jar in your system is corrupted. I guess this can happen due to instabilities in IPEA's server during download. Another possible reason is that you may be using incompatible versions of r5r and R5 Jar files, perhaps due to a manual install.
In any case, running `download_r5(force_update = TRUE)` should fix it, but that depends on the server (which unfortunately seems to be down again at the moment).

**Comment by jamaps** [comment]
Hi there, 

I ran into the same problem, tried running the force update, but I'm now getting the following error:

```
> download_r5(force_update = TRUE)
Problem connecting to data server.
Problem connecting to the data server. Please try again in a few minutes.
```

I was just going to wait until the server was up again, but I was also wondering if the appropriate R5 jar file can be downloaded from elsewhere?

**Comment by rafapereirabr** [comment]
Hi @jamaps , we're looking into this right now. As you know, currently, we compile Conveyal's R5 jar files and store them on our server.  Ideally, we would prefer to download the original R5 jar files compiled and released by Conveyal on a public repository. We're in contact with them about this. If that's not possible, we will probably move the JAR files to another place real soon.

**Comment by rafapereirabr** [comment]
Hi all. We just published a new verion of r5r v0.7.0 on CRAN. This issue should be fixed with this new version.

**Comment by rafapereirabr** [comment]
Closing this issue for now, but please let us know if the problem persists on your side.

**Comment by randl068** [comment]
Unfortunately the problem persists despite the force update. Any idea what else might be causing the problem?

**Comment by rafapereirabr** [comment]
@randl068 , could you please run `sessionInfo()` on your R session and paste the output in a comment below?

**Comment by randl068** [comment]
Pasted below. If it helps, I think I've gotten a temporary fix by manually downloading the jar version 6.6 and renaming it to 6.4 in the /jar folder.

> R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 17763)
Matrix products: default locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     
other attached packages:
[1] ggplot2_3.3.5     data.table_1.14.2 sf_1.0-5         
[4] r5r_0.7.0        
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8         compiler_4.0.3    
 [3] pillar_1.7.0       class_7.3-17      
 [5] tools_4.0.3        lifecycle_1.0.1   
 [7] tibble_3.1.6       gtable_0.3.0      
 [9] checkmate_2.0.0    pkgconfig_2.0.3   
[11] rlang_1.0.1        DBI_1.1.2         
[13] cli_3.1.1          curl_4.3.2        
[15] rJava_1.0-6        e1071_1.7-9       
[17] withr_2.4.3        vctrs_0.3.8       
[19] classInt_0.4-3     grid_4.0.3        
[21] glue_1.6.1         R6_2.5.1          
[23] fansi_1.0.2        magrittr_2.0.2    
[25] scales_1.1.1       backports_1.4.1   
[27] ellipsis_0.3.2     units_0.7-2       
[29] colorspace_2.0-2   KernSmooth_2.23-17
[31] utf8_1.2.2         proxy_0.4-26      
[33] munsell_0.5.0      crayon_1.5.0

**Comment by abdulrr** [comment]
Hi there, I ran into the same problem, I tried all the proposed options above with no success.
Can someone please look into this? 

The persisting error:
```
Error in rJava::.jnew("org.ipea.r5r.R5RCore", data_path, verbose) : 
  java.lang.NoClassDefFoundError: com/conveyal/r5/analyst/decay/DecayFunction
```

**Comment by rafapereirabr** [comment]
@abdulrr , could you please run sessionInfo() on your R session and paste the output in a comment below?

**Comment by abdulrr** [comment]
session info is below. I also tried the same script on a Mac OS, and it worked. I wonder why it doesn't work on my windows.

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] r5r_0.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8          rstudioapi_0.11     magrittr_2.0.2.9000 units_0.8-0         tidyselect_1.1.0   
 [6] R6_2.5.0            rlang_0.4.9         httr_1.4.2          dplyr_1.0.2         tools_4.0.3        
[11] grid_4.0.3          checkmate_2.0.0     data.table_1.13.6   KernSmooth_2.23-17  e1071_1.7-9        
[16] DBI_1.1.0           ellipsis_0.3.1      class_7.3-17        tibble_3.0.4        lifecycle_0.2.0    
[21] crayon_1.3.4        sf_1.0-3            rJava_0.9-13        purrr_0.3.4         vctrs_0.3.5        
[26] curl_4.3            glue_1.4.2          proxy_0.4-26        compiler_4.0.3      pillar_1.4.7       
[31] backports_1.4.1     generics_0.1.0      classInt_0.4-3      pkgconfig_2.0.3    
```

**Comment by mvpsaraiva** [comment]
Hi @abdulrr. I only saw this error message when the R5 Jar file is corrupted in some way. Try running the following lines to see what's inside the package's folder in your system and paste the results in a comment below. There should be a file named `r5-v6.4-all.jar` which size is around 46 MB (it shows exactly 46842628 bytes in my system). If it's smaller than that, it may be corrupted.

```R
path <- system.file("jar", package = "r5r")
file.info(list.files(path, full.names = T))
```

The solution is really to redownload the jar with `r5r::download_r5(force_update = TRUE)` or, even better, removing the entire package and reinstalling again. You can use the script that @rafapereirabr posted a few comments back, but change the line:
```R
r5r_core <- setup_r5(data_path = data_path, temp_dir = TRUE)
```
to:
```R
r5r_core <- setup_r5(data_path = data_path, temp_dir = FALSE)
```
This will save a new jar inside the folder where the package is installed, in a more permanent way. Let us know if some of this works.

**Comment by abdulrr** [comment]
Thanks @mvpsaraiva! Now it works.
You are right, the R5 jar file wasn't downloaded correctly for some reason. I only had 4 MBs size for my jar file. Even with `r5r::download_r5(force_update = TRUE)`. I had to manually download it from [](https://github.com/ipeaGIT/r5/releases/download/v6.4/r5-v6.4-all.jar) The download takes longer than expected for some reason and I think that might be the reason it wasn't downloaded correctly.

**Comment by zoezhiyi** [comment]
Hi there, I ran into the same problem, I tried all the proposed options above with no success, and I'm now getting the following error:

> Error in setup_r5(data_path = File_path, verbose = TRUE) : 
  java.lang.NoClassDefFoundError: javax/naming/NamingException

Can someone look into this please?

**Comment by rafapereirabr** [comment]
1. What version of `r5r` are you using? 
2.  Have you tried running `r5r::download_r5(force_update = TRUE)` ?
3. What version of Java you using?

Check you java version
```
rJava::.jinit()
rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")

```

**Comment by zoezhiyi** [comment]
Hi @rafapereirabr, the version of r5r is r5r_0.7.1.
I tried running r5r::download_r5(force_update = TRUE), but error still occured.
The following is my java version.

>  rJava::.jinit()
[1] 0
> rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")
[1] "11.0.16.1"

**Comment by rafapereirabr** [comment]
That's strange
I haven't tried `r5r` with JDK 11.0.16.1, but I know for sure that `r5r`runs fine with JDK `v11.0.10`. I would suggest you try the following steps:

1. Uninstall r5r by running utils::remove.packages('r5r')
2. Restart your R session
3. Install r5r from CRAN: install.packages("r5r")
4. Try running the code below:

```
library(r5r)

# build transport network
data_path <- system.file("extdata/spo", package = "r5r")
r5r_core <- setup_r5(data_path = data_path, temp_dir = TRUE)

# load origin/destination points
points <- read.csv(file.path(data_path, "spo_hexgrid.csv"))[1:5,]

departure_datetime <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")

# estimate travel time matrix
ttm <- travel_time_matrix(r5r_core,
                         origins = points,
                         destinations = points,
                         mode = c("WALK", "TRANSIT"),
                         departure_datetime = departure_datetime,
                         max_trip_duration = 90)

head(ttm)
```

**Comment by zoezhiyi** [comment]
Hi @rafapereirabr , the same error occured.

> Error in setup_r5(data_path = data_path, temp_dir = TRUE) : 
  java.lang.NoClassDefFoundError: javax/naming/NamingException

**Comment by mvpsaraiva** [comment]
Hi @zoezhiyi. Try running these lines of code to check if R5's jar is installed within the package, and if the file is the correct size. This error usually happens when R5's jar is corrupted.

```R
path <- system.file("jar", package = "r5r")
file.info(list.files(path, full.names = T))
```

**Comment by zoezhiyi** [comment]
Hi, @mvpsaraiva .
I think there might be something wrong, could you please help me to solve this problem?
Thanks in advance.
`> path <- system.file("jar", package = "r5r")
> file.info(list.files(path, full.names = T))
                                                                          size
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml     898
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar 52010
                                                                         isdir
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml   FALSE
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar FALSE
                                                                         mode
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml    666
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar  666
                                                                                       mtime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml   2022-10-06 14:34:16
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar 2022-10-06 14:34:16
                                                                                       ctime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml   2022-10-06 14:34:16
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar 2022-10-06 14:34:16
                                                                                       atime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml   2022-10-06 14:34:16
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar 2022-10-06 14:35:12
                                                                         exe
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml    no
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar  no`

**Comment by mvpsaraiva** [comment]
I don't see R5´s jar in the list of files provided. Try running `setup_r5()` with `temp_dir = FALSE`.

**Comment by zoezhiyi** [comment]
Error occured.
`> r5r_core <- setup_r5(data_path = data_path, temp_dir = False)
Error in checkmate::assert_logical(temp_dir) : object 'False' not found`

**Comment by mvpsaraiva** [comment]
`FALSE` must be spelled in capital letters.

**Comment by mvpsaraiva** [comment]
Now run the list.files thing again, to check if R5 was downloaded

**Comment by zoezhiyi** [comment]
```
    size
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml          898
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar 46842628
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar      52010
                                                                           isdir
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml     FALSE
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar FALSE
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar   FALSE
                                                                           mode
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml      666
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar  666
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar    666
                                                                                         mtime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml     2022-10-06 14:34:16
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar 2022-10-06 15:59:29
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar   2022-10-06 14:34:16
                                                                                         ctime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml     2022-10-06 14:34:16
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar 2022-10-06 15:59:25
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar   2022-10-06 14:34:16
                                                                                         atime
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml     2022-10-06 15:41:22
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar 2022-10-06 15:59:30
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar   2022-10-06 15:59:30
                                                                           exe
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/logback.xml      no
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5-v6.4-all.jar  no
D:/Users/Zhiyi/AppData/Programs/R/Program Data/lib/r5r/jar/r5r_0_6_0.jar    no
```

**Comment by zoezhiyi** [comment]
Hi @mvpsaraiva ,the above is the result of my run. Could you please help me see what's wrong?
Thanks a lot.

**Comment by mvpsaraiva** [comment]
Hi @zoezhiyi. I still don't know what's going on, and I can't do further tests today. Maybe you can try using the development version of r5r, installing it from GitHub. Just keep in mind that the newest version has changes that may require you to adapt old code.

**Comment by zoezhiyi** [comment]
Hi @rafapereirabr , I ran the code you recommanded, but the same error occured when I ran `r5r_core <- setup_r5(data_path = data_path, temp_dir = FALSE)`.
The following is the response of sessionInfo().
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] r5r_0.7.90000     devtools_2.4.4    usethis_2.1.6    
[4] rJava_1.0-6       mapview_2.11.0    ggplot2_3.3.6    
[7] openxlsx_4.2.5    data.table_1.14.2 sf_1.0-8         

loaded via a namespace (and not attached):
 [1] httr_1.4.4         pkgload_1.3.0      shiny_1.7.2       
 [4] sp_1.5-0           stats4_4.2.1       remotes_2.4.2     
 [7] sessioninfo_1.2.2  backports_1.4.1    pillar_1.8.1      
[10] lattice_0.20-45    glue_1.6.2         digest_0.6.29     
[13] promises_1.2.0.1   checkmate_2.1.0    colorspace_2.0-3  
[16] htmltools_0.5.3    httpuv_1.6.6       pkgconfig_2.0.3   
[19] raster_3.6-3       purrr_0.3.4        xtable_1.8-4      
[22] scales_1.2.1       webshot_0.5.4      processx_3.7.0    
[25] terra_1.6-17       satellite_1.0.4    later_1.3.0       
[28] tibble_3.1.8       proxy_0.4-27       ellipsis_0.3.2    
[31] cachem_1.0.6       withr_2.5.0        cli_3.4.1         
[34] magrittr_2.0.3     crayon_1.5.2       mime_0.12         
[37] memoise_2.0.1      ps_1.7.1           fs_1.5.2          
[40] fansi_1.0.3        class_7.3-20       pkgbuild_1.3.1    
[43] profvis_0.3.7      tools_4.2.1        prettyunits_1.1.1 
[46] lifecycle_1.0.2    stringr_1.4.1      munsell_0.5.0     
[49] zip_2.2.1          callr_3.7.2        compiler_4.2.1    
[52] e1071_1.7-11       rlang_1.0.6        classInt_0.4-8    
[55] units_0.8-0        grid_4.2.1         rstudioapi_0.14   
[58] htmlwidgets_1.5.4  crosstalk_1.2.0    miniUI_0.1.1.1    
[61] leafem_0.2.0       base64enc_0.1-3    gtable_0.3.1      
[64] codetools_0.2-18   DBI_1.1.3          curl_4.3.2        
[67] R6_2.5.1           fastmap_1.1.0      utf8_1.2.2        
[70] rprojroot_2.0.3    KernSmooth_2.23-20 stringi_1.7.8     
[73] Rcpp_1.0.9         vctrs_0.4.2        png_0.1-7         
[76] leaflet_2.1.1      urlchecker_1.0.1  
```

**Comment by zoezhiyi** [comment]
Hi there, I solved the problem when I unstalled Java 11.0.16.1 and installed Java 11.0.10. Thanks for your time! @mvpsaraiva @rafapereirabr
